import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

interface LanguageProviderProps {
  children: ReactNode;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.marketplace': 'Marketplace',
    'nav.bouquetBuilder': 'Bouquet Builder',
    'nav.giftBoxes': 'Gift Boxes',
    'nav.occasions': 'Occasions',
    'nav.partners': 'Partners',
    'nav.admin': 'Admin',
    'nav.signIn': 'Sign In',
    'nav.profile': 'Profile Settings',
    'nav.logout': 'Log out',
    'nav.categories': 'Categories',
    'categories.naturalRoses': 'Natural Roses',
    'categories.giftBoxes': 'Gift Boxes',
    'categories.weddingServices': 'Wedding Services',
    'categories.bridalBouquets': 'Bridal Bouquets',
    'categories.specialOccasions': 'Special Occasions',
    'categories.premiumFlowers': 'Premium Flowers',
    'categories.wedding': 'Wedding',
    'categories.occasions': 'Occasions',
    'builder.customizeRibbon': 'Customize Ribbon',
    'builder.addCard': 'Add Card',
    'builder.flowerColors': 'Flower Colors',
    'builder.arrangement': 'Arrangement',
    'builder.price': 'Price',
    'builder.addToCart': 'Add to Cart',
    'builder.save': 'Save',
    'builder.share': 'Share',
    'builder.clear': 'Clear',
    'common.customGift': 'Create Custom Gift',
    'common.items': 'items',
    'common.search': 'Search flowers, bouquets, occasions...',
    'common.shopNow': 'Shop Now',
    'common.browseCategories': 'Browse Categories',
    'common.addToCart': 'Add to Cart',
    'common.viewAll': 'View All',
    'common.loadMore': 'Load More Products',
    'common.clearFilters': 'Clear All Filters',
    'common.noResults': 'No products match your current filters',
    'common.freshToday': 'Fresh Today',
    'common.bestSellers': 'Best Sellers',
    'common.featuredFlowers': 'Featured Flowers',
    'common.searchResults': 'Search Results for',
    'common.shopByCategory': 'Shop by Category',
    'common.discoverCollection': 'Discover our beautiful collection organized by occasions and flower types',
    'common.cantFind': 'Can\'t Find What You\'re Looking For?',
    'common.createCustom': 'Create a completely custom bouquet or gift box with our interactive builder. Choose your flowers, colors, and arrangements exactly how you want them.',
    'common.startCustomDesign': 'Start Custom Design',
    'common.browseCategory': 'Browse Category',
    'common.availableFlowers': 'Available Flowers',
    'common.designBouquet': 'Design Your Bouquet',
    'common.baseBouquet': 'Base bouquet',
    'common.flowers': 'Flowers',
    'common.wrapping': 'Wrapping',
    'common.ribbon': 'Ribbon',
    'common.customCard': 'Custom Card',
    'common.total': 'Total',
    'common.color': 'Color',
    'common.width': 'Width',
    'common.style': 'Style',
    'common.message': 'Message',
    'common.fontStyle': 'Font Style',
    'common.design': 'Design',
    'common.arrangementStyle': 'Arrangement Style',
    'common.narrow': 'Narrow',
    'medium': 'Medium',
    'common.wide': 'Wide',
    'common.satin': 'Satin',
    'common.silk': 'Silk',
    'common.burlap': 'Burlap',
    'common.velvet': 'Velvet',
    'common.elegant': 'Elegant',
    'common.modern': 'Modern',
    'common.classic': 'Classic',
    'common.handwritten': 'Handwritten',
    'common.simple': 'Simple',
    'common.floral': 'Floral',
    'common.vintage': 'Vintage',
    'common.minimalist': 'Minimalist',
    'common.tightCluster': 'Tight Cluster',
    'common.looseNatural': 'Loose Natural',
    'common.cascading': 'Cascading',
    'common.domeShape': 'Dome Shape',
    'common.paper': 'Paper',
    'common.cellophane': 'Cellophane',
    'common.saveCustomBouquet': 'Save Custom Bouquet',
    'common.saveDescription': 'Save your beautiful creation to access it later or share with others.',
    'common.bouquetName': 'Bouquet Name',
    'common.description': 'Description (Optional)',
    'common.cancel': 'Cancel',
    'common.saveBouquet': 'Save Bouquet',
    'common.addedToCart': 'Added to Cart',
    'common.addedToFavorites': 'Added to Favorites',
    'common.removedFromFavorites': 'Removed from Favorites',
    'common.bouquetCleared': 'Bouquet cleared',
    'common.pleaseAddFlowers': 'Please add flowers to your bouquet first',
    'common.customBouquetAdded': 'Custom bouquet added to cart!',
    'common.flowerAdded': 'added to bouquet',
  },
  ar: {
    'nav.marketplace': 'السوق',
    'nav.bouquetBuilder': 'صانع الباقات',
    'nav.giftBoxes': 'صناديق الهدايا',
    'nav.occasions': 'المناسبات',
    'nav.partners': 'الشركاء',
    'nav.admin': 'الإدارة',
    'nav.signIn': 'تسجيل الدخول',
    'nav.profile': 'إعدادات الملف الشخصي',
    'nav.logout': 'تسجيل الخروج',
    'nav.categories': 'الفئات',
    'categories.naturalRoses': 'الورود الطبيعية',
    'categories.giftBoxes': 'صناديق الهدايا',
    'categories.weddingServices': 'خدمات الأعراس',
    'categories.bridalBouquets': 'باقات العروس',
    'categories.specialOccasions': 'المناسبات الخاصة',
    'categories.premiumFlowers': 'الورود الفاخرة',
    'categories.wedding': 'الأعراس',
    'categories.occasions': 'المناسبات',
    'builder.customizeRibbon': 'تخصيص الشريط',
    'builder.addCard': 'إضافة بطاقة',
    'builder.flowerColors': 'ألوان الورود',
    'builder.arrangement': 'التنسيق',
    'builder.price': 'السعر',
    'builder.addToCart': 'إضافة للسلة',
    'builder.save': 'حفظ',
    'builder.share': 'مشاركة',
    'builder.clear': 'مسح',
    'common.customGift': 'إنشاء هدية مخصصة',
    'common.items': 'عناصر',
    'common.search': 'البحث عن الورود، الباقات، المناسبات...',
    'common.shopNow': 'تسوق الآن',
    'common.browseCategories': 'تصفح الفئات',
    'common.addToCart': 'إضافة للسلة',
    'common.viewAll': 'عرض الكل',
    'common.loadMore': 'تحميل المزيد من المنتجات',
    'common.clearFilters': 'مسح جميع المرشحات',
    'common.noResults': 'لا توجد منتجات تطابق المرشحات الحالية',
    'common.freshToday': 'طازج اليوم',
    'common.bestSellers': 'الأكثر مبيعاً',
    'common.featuredFlowers': 'الورود المميزة',
    'common.searchResults': 'نتائج البحث عن',
    'common.shopByCategory': 'تسوق حسب الفئة',
    'common.discoverCollection': 'اكتشف مجموعتنا الجميلة المنظمة حسب المناسبات وأنواع الزهور',
    'common.cantFind': 'لا تجد ما تبحث عنه؟',
    'common.createCustom': 'أنشئ باقة أو صندوق هدايا مخصص تماماً باستخدام منشئنا التفاعلي. اختر زهورك وألوانك وترتيباتك بالضبط كما تريدها.',
    'common.startCustomDesign': 'ابدأ التصميم المخصص',
    'common.browseCategory': 'تصفح الفئة',
    'common.availableFlowers': 'الزهور المتاحة',
    'common.designBouquet': 'صمم باقاتك',
    'common.baseBouquet': 'الباقة الأساسية',
    'common.flowers': 'الزهور',
    'common.wrapping': 'التغليف',
    'common.ribbon': 'الشريط',
    'common.customCard': 'البطاقة المخصصة',
    'common.total': 'المجموع',
    'common.color': 'اللون',
    'common.width': 'العرض',
    'common.style': 'النمط',
    'common.message': 'الرسالة',
    'common.fontStyle': 'نمط الخط',
    'common.design': 'التصميم',
    'common.arrangementStyle': 'نمط الترتيب',
    'common.narrow': 'ضيق',
    'medium': 'متوسط',
    'common.wide': 'واسع',
    'common.satin': 'ساتان',
    'common.silk': 'حرير',
    'common.burlap': 'خيش',
    'common.velvet': 'مخمل',
    'common.elegant': 'أنيق',
    'common.modern': 'حديث',
    'common.classic': 'كلاسيكي',
    'common.handwritten': 'خط اليد',
    'common.simple': 'بسيط',
    'common.floral': 'زهري',
    'common.vintage': 'عتيق',
    'common.minimalist': 'بسيط',
    'common.tightCluster': 'عنقود ضيق',
    'common.looseNatural': 'طبيعي فضفاض',
    'common.cascading': 'متتالي',
    'common.domeShape': 'شكل القبة',
    'common.paper': 'ورق',
    'common.cellophane': 'سيلوفان',
    'common.saveCustomBouquet': 'حفظ الباقة المخصصة',
    'common.saveDescription': 'احفظ إبداعك الجميل للوصول إليه لاحقاً أو مشاركته مع الآخرين.',
    'common.bouquetName': 'اسم الباقة',
    'common.description': 'الوصف (اختياري)',
    'common.cancel': 'إلغاء',
    'common.saveBouquet': 'حفظ الباقة',
    'common.addedToCart': 'تمت الإضافة للسلة',
    'common.addedToFavorites': 'تمت الإضافة للمفضلة',
    'common.removedFromFavorites': 'تم الحذف من المفضلة',
    'common.bouquetCleared': 'تم مسح الباقة',
    'common.pleaseAddFlowers': 'يرجى إضافة زهور إلى باقاتك أولاً',
    'common.customBouquetAdded': 'تمت إضافة الباقة المخصصة للسلة!',
    'common.flowerAdded': 'تمت إضافة الزهرة للباقة',
  },
  fr: {
    'nav.marketplace': 'Marché',
    'nav.bouquetBuilder': 'Créateur de Bouquet',
    'nav.giftBoxes': 'Coffrets Cadeaux',
    'nav.occasions': 'Occasions',
    'nav.partners': 'Partenaires',
    'nav.admin': 'Admin',
    'nav.signIn': 'Se Connecter',
    'nav.profile': 'Paramètres du Profil',
    'nav.logout': 'Se Déconnecter',
    'nav.categories': 'Catégories',
    'categories.naturalRoses': 'Roses Naturelles',
    'categories.giftBoxes': 'Coffrets Cadeaux',
    'categories.weddingServices': 'Services de Mariage',
    'categories.bridalBouquets': 'Bouquets de Mariée',
    'categories.specialOccasions': 'Occasions Spéciales',
    'categories.premiumFlowers': 'Fleurs Premium',
    'categories.wedding': 'Mariage',
    'categories.occasions': 'Occasions',
    'builder.customizeRibbon': 'Personnaliser le Ruban',
    'builder.addCard': 'Ajouter une Carte',
    'builder.flowerColors': 'Couleurs des Fleurs',
    'builder.arrangement': 'Arrangement',
    'builder.price': 'Prix',
    'builder.addToCart': 'Ajouter au Panier',
    'builder.save': 'Sauvegarder',
    'builder.share': 'Partager',
    'builder.clear': 'Effacer',
    'common.customGift': 'Créer un Cadeau Personnalisé',
    'common.items': 'articles',
    'common.search': 'Rechercher des fleurs, bouquets, occasions...',
    'common.shopNow': 'Acheter Maintenant',
    'common.browseCategories': 'Parcourir les Catégories',
    'common.addToCart': 'Ajouter au Panier',
    'common.viewAll': 'Voir Tout',
    'common.loadMore': 'Charger Plus de Produits',
    'common.clearFilters': 'Effacer Tous les Filtres',
    'common.noResults': 'Aucun produit ne correspond à vos filtres actuels',
    'common.freshToday': 'Frais Aujourd\'hui',
    'common.bestSellers': 'Meilleures Ventes',
    'common.featuredFlowers': 'Fleurs en Vedette',
    'common.searchResults': 'Résultats de Recherche pour',
    'common.shopByCategory': 'Acheter par Catégorie',
    'common.discoverCollection': 'Découvrez notre belle collection organisée par occasions et types de fleurs',
    'common.cantFind': 'Vous ne trouvez pas ce que vous cherchez ?',
    'common.createCustom': 'Créez un bouquet ou un coffret cadeau entièrement personnalisé avec notre créateur interactif. Choisissez vos fleurs, couleurs et arrangements exactement comme vous les voulez.',
    'common.startCustomDesign': 'Commencer le Design Personnalisé',
    'common.browseCategory': 'Parcourir la Catégorie',
    'common.availableFlowers': 'Fleurs Disponibles',
    'common.designBouquet': 'Concevez Votre Bouquet',
    'common.baseBouquet': 'Bouquet de base',
    'common.flowers': 'Fleurs',
    'common.wrapping': 'Emballage',
    'common.ribbon': 'Ruban',
    'common.customCard': 'Carte Personnalisée',
    'common.total': 'Total',
    'common.color': 'Couleur',
    'common.width': 'Largeur',
    'common.style': 'Style',
    'common.message': 'Message',
    'common.fontStyle': 'Style de Police',
    'common.design': 'Design',
    'common.arrangementStyle': 'Style d\'Arrangement',
    'common.narrow': 'Étroit',
    'medium': 'Moyen',
    'common.wide': 'Large',
    'common.satin': 'Satin',
    'common.silk': 'Soie',
    'common.burlap': 'Toile de Jute',
    'common.velvet': 'Velours',
    'common.elegant': 'Élégant',
    'common.modern': 'Moderne',
    'common.classic': 'Classique',
    'common.handwritten': 'Manuscrit',
    'common.simple': 'Simple',
    'common.floral': 'Floral',
    'common.vintage': 'Vintage',
    'common.minimalist': 'Minimaliste',
    'common.tightCluster': 'Groupe Serré',
    'common.looseNatural': 'Naturel Détendu',
    'common.cascading': 'Cascading',
    'common.domeShape': 'Forme de Dôme',
    'common.paper': 'Papier',
    'common.cellophane': 'Cellophane',
    'common.saveCustomBouquet': 'Sauvegarder le Bouquet Personnalisé',
    'common.saveDescription': 'Sauvegardez votre belle création pour y accéder plus tard ou la partager avec d\'autres.',
    'common.bouquetName': 'Nom du Bouquet',
    'common.description': 'Description (Optionnelle)',
    'common.cancel': 'Annuler',
    'common.saveBouquet': 'Sauvegarder le Bouquet',
    'common.addedToCart': 'Ajouté au Panier',
    'common.addedToFavorites': 'Ajouté aux Favoris',
    'common.removedFromFavorites': 'Retiré des Favoris',
    'common.bouquetCleared': 'Bouquet effacé',
    'common.pleaseAddFlowers': 'Veuillez d\'abord ajouter des fleurs à votre bouquet',
    'common.customBouquetAdded': 'Bouquet personnalisé ajouté au panier !',
    'common.flowerAdded': 'fleur ajoutée au bouquet',
  },
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('preferred-language') as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('preferred-language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        dir: language === 'ar' ? 'rtl' : 'ltr',
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};