// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apbfdrwneoohudetgcve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwYmZkcnduZW9vaHVkZXRnY3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzUzMTcsImV4cCI6MjA3MzU1MTMxN30.Kb6jTiw5g3JDh74sVsySf4p87LqBrfOmfN40oR-gN1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});